title: Data for Education Systems
description: A guide to designing and implementing better data systems for education
theme: just-the-docs
lang: en_IN
url: https://data4edu.systems
categories: [data-to-action]

favicon_ico: /assets/images/D4ES.png

aux_links:
  View on GitHub: https://github.com/data4edu/data4edu.github.io/
aux_links_new_tab: true

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e, %Y"

plugins:
  - jekyll-target-blank

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: yellow

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 4
  # Maximum amount of previews per search result
  # Default: 3
  previews: 5
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: false
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false