title: Data for Education Systems
description: A guide to designing and implementing better data systems for education
theme: just-the-docs

url: https://data4edu.github.io

logo: "/assets/images/bar-chart-line.svg"


aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
